name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Can MSI install from the internet?
      run: |
        msiexec /i https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi /qn /norestart /L*v! "C:\msilog.log"
    - run: type C:\msilog.log

